glslc base.vert -o base.vert.spv
glslc base.frag -o base.frag.spv
glslc composite.vert -o composite.vert.spv
glslc composite.frag -o composite.frag.spv
glslc Deferred.vert -o Deferred.vert.spv
glslc Deferred.frag -o Deferred.frag.spv
glslc DeferredLightning.vert -o DeferredLightning.vert.spv
glslc DeferredLightning.frag -o DeferredLightning.frag.spv
glslc ShadowMap.vert -o ShadowMap.vert.spv
glslc ShadowMap.frag -o ShadowMap.frag.spv
glslc unlit.vert -o unlit.vert.spv
glslc unlit.frag -o unlit.frag.spv
